- name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    groups: admins,developers
    append: yes

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/ansible/.ssh/id_ed25519.pub') }}"