- name: Instalando a ultima vesão dos pacotes Vim, nano, unzip, mtr,nmap,whois
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
    ansible.builtin.package:
      name:
        - vim
      state: latest